# Generated by Django 5.0.7 on 2024-07-28 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('p', 'Perro'), ('g', 'Gato'), ('o', 'Otro')], default='p', max_length=1)),
                ('edad', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('m', 'Macho'), ('h', 'Hembra')], default='m', max_length=1)),
                ('fecha_ingreso', models.DateTimeField()),
                ('lugar_rescate', models.TextField()),
                ('para_adopcion', models.BooleanField(default=False)),
                ('voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='voluntarios.voluntario')),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adopcion', models.DateField()),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.adoptante')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('fecha_vacunacion', models.DateField()),
                ('lugar_vacunacion', models.TextField()),
                ('doctor', models.CharField(max_length=100)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
    ]
