# Generated by Django 5.0.7 on 2024-07-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaPerdida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_perdida', models.DateField()),
                ('nombre_propietario', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=15)),
            ],
        ),
    ]
